[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  "programs/addin-mock",
  "programs/addin-api",
  "programs/p-addin-api",
  "programs/governance",
  "programs/p-governance",
  "programs/test-sdk",
  "programs/tools",
  "programs/p-tools",
  "programs/p-token-2022",
  "programs/chat",
  "programs/transfer-hook/example",
  "programs/utils/crate",
  "programs/utils/macro",
]

exclude = []

resolver = "2"


[workspace.dependencies]
solana-program = "2.1.7"
borsh = "1.5.1"
spl-token-2022 = { version = "6.0.0", features = ["no-entrypoint"] }
solana-program-test = "2.1.7"
solana-sdk = "2.1.7"
solana-account-decoder = "2.1.7"
solana-clap-v3-utils = "2.1.7"
solana-cli-config = "2.1.7"
solana-cli-output = "2.1.7"
solana-client = "2.1.7"
solana-logger = "2.1.7"
solana-remote-wallet = "2.1.7"
solana-transaction-status = "2.1.7"
solana-vote-program = "2.1.7"
solana-test-validator = "2.1.7"
solana-clap-utils = "2.1.7"
solana-banks-interface = "2.1.7"
solana-rpc-client = "2.1.7"
solana-rpc-client-api = "2.1.7"
solana-zk-token-sdk = "2.1.7"
spl-tlv-account-resolution = "0.9.0"
spl-transfer-hook-interface = "0.9.0"
spl-token-client = "0.13.0"
spl-token = "4.0" 
quote = "1.0"
regex = "1"
syn = "1.0"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]